const english = {
  problemTitle: "You saved it\nfor later.\nBut later\nnever came.",
  problemExamples: ["That new café everyone’s talking about.", "That concert you want to see in 3 months.", "Something you  you’d buy later."],
  problemSources: ["Saved post", "Screenshot", "Somewhere in a chat"],
  problemPain: "You remember saving them. Just not where.",
  problemSolution: "brings your finds together, so you can spend less time looking for the thing you saved and more time actually coming back to it.",
  steps: [
    { title: "Save a find", description: "Share a post, paste a link, or add a screenshot. Bring the things you find in different apps into one place." },
    { title: "Add what matters", description: "Name it, tag it, or add a location. Keep the context that helps you remember what it is and why you saved it." },
    { title: "Come back when it counts", description: "Search when you’re ready, or set a reminder for the right time. Your saves stay easy to find when you actually need them." },
  ],
  mapLead: "Heading out and wondering what’s nearby? Open the map to see the places you’ve already saved around you — from a café you wanted to try to a spot you meant to visit.",
  mapDetail: "No digging through screenshots or trying to remember which app you saw it in.",
  mapAlt: "Pocklet map showing saved places nearby",
  howTitle: "Save it. Find it. Do it.",
  mapTitle: "See what you saved around you",
  featuresTitle: "The boring parts, handled.",
  features: [
    { title: "Save from wherever you find it", description: "Share a link from Instagram, TikTok, or anywhere else. Keep it together with your other finds." },
    { title: "Categories that fit life", description: "Eat, Go, Buy, Do, or create your own categories when you need them." },
    { title: "Find it without remembering where", description: "Search titles, notes, tags, links and available text from your saves." },
    { title: "Come back at the right time", description: "Set a reminder for something you don’t want to forget." },
    { title: "Keep the good ones", description: "Keep the best ones easy to find. Favourites stay accessible even after you complete them." },
    { title: "Done doesn’t mean gone", description: "Mark a find done, favourite the ones you loved, and look back anytime in History." },
  ],
  downloadDescription: "Keep the things you like easy to come back to — whether that’s this weekend or a few months from now.",
  appStoreComingSoon: "Coming soon",
  googlePlayQrAlt: "Scan to download Pocklet on Google Play",
  plusTitle: "More room.\nLess work.",
  plusDescription: "Keep every find, let AI handle the details, and choose exactly when Pocklet brings things back.",
  plusAutoTitle: "Unlimited saves & Auto Details",
  plusAutoDescription: "Keep every find without a limit. Auto Details suggests the title, notes, category, tags and location. Review and change anything it finds.",
  plusReminderTitle: "Smarter reminders",
  plusReminderDescription: "Pick the exact reminder time and add multiple nudges before it matters.",
};

type DesktopHomepageCopy = typeof english;

export const desktopHomepageCopy: Record<string, DesktopHomepageCopy> = {
  en: english,
  "zh-TW": {
    problemTitle: "想做的那件事，\n還躺在某個角落。",
    problemExamples: ["那間最近大家都在聊的咖啡廳", "三個月後想去的那場演唱會", "那個一直說之後要買的東西"],
    problemSources: ["收藏的貼文", "截圖", "某段聊天裡"],
    problemPain: "明明記得有存下來，要找時卻怎麼都找不到。",
    problemSolution: "把好發現收在一起，少花時間翻找，多一點時間回到那些一直想做的事。",
    steps: [
      { title: "看到喜歡的就收進來", description: "分享貼文、貼上連結，或加入截圖。把不同 App 裡的好發現，都收在同一個地方。" },
      { title: "補上重要資訊", description: "加個名稱、標籤，也可以標記地點。留住重要的細節，讓你記得當初為什麼想存下來。" },
      { title: "需要時再回來", description: "想用時直接搜尋，或先設好提醒。真的需要時，收藏就在手邊。" },
    ],
    mapLead: "準備出門，想知道附近有什麼？打開地圖，就能看到周圍存過的地方，從想試試的咖啡廳，到一直想去的景點。",
    mapDetail: "不用翻截圖，也不用回想當初是在哪個 App 看到的。",
    mapAlt: "Pocklet 地圖上的附近收藏地點",
    howTitle: "存下來。找回來。真的去做。",
    mapTitle: "看看附近存過哪些地方",
    featuresTitle: "瑣碎的事，都幫你搞定。",
    features: [
      { title: "在哪看到，都能存", description: "從 Instagram、TikTok 或其他地方分享連結，把好發現和其他收藏收在一起。" },
      { title: "貼近生活的分類", description: "吃、去、買、做，也可以建立自己的分類。" },
      { title: "不用記得存在哪裡", description: "搜尋收藏的名稱、筆記、標籤、連結，以及可辨識的文字。" },
      { title: "在對的時間回來", description: "替不想忘記的事設好提醒。" },
      { title: "喜歡的，留在最愛", description: "把最喜歡的收藏留在手邊，就算完成了，還是能輕鬆找到。" },
      { title: "做完了，也還在", description: "標記完成，把喜歡的加入最愛，隨時到紀錄裡回顧。" },
    ],
    downloadDescription: "把發現的好東西存起來，這個週末或幾個月後想再看看時，都能輕鬆找回。",
    appStoreComingSoon: "即將推出",
    googlePlayQrAlt: "掃描 QR Code，到 Google Play 下載 Pocklet",
    plusTitle: "多一點空間，\n少一點瑣事。",
    plusDescription: "好發現都存下來，細節交給 AI，提醒時間也能自己決定。",
    plusAutoTitle: "無限收藏與 Auto Details",
    plusAutoDescription: "想存多少都可以。Auto Details 會建議名稱、筆記、分類、標籤和地點，你可以檢查並修改任何資訊。",
    plusReminderTitle: "更靈活的提醒",
    plusReminderDescription: "選擇確切的提醒時間，還能加入多次提前提醒。",
  },
  "zh-CN": {
    problemTitle: "想做的那件事，\n还躺在某个角落。",
    problemExamples: ["那家最近大家都在聊的咖啡店", "三个月后想去的那场演唱会", "那个一直说之后要买的东西"],
    problemSources: ["收藏的内容", "截图", "某段聊天里"],
    problemPain: "明明记得存过，真要找的时候却怎么都找不到。",
    problemSolution: "把好发现放在一起，少花时间翻找，多一点时间回到那些一直想做的事。",
    steps: [
      { title: "看到喜欢的就收进来", description: "分享内容、粘贴链接，或添加截图。把不同 App 里的好发现，都放在同一个地方。" },
      { title: "补上重要信息", description: "加个名称、标签，也可以标记地点。留下重要的细节，让你记得当初为什么想存下来。" },
      { title: "需要时再回来", description: "想用时直接搜索，或提前设好提醒。真正需要时，收藏就在手边。" },
    ],
    mapLead: "准备出门，想知道附近有什么？打开地图，就能看到周围存过的地方，从想试试的咖啡店，到一直想去的景点。",
    mapDetail: "不用翻截图，也不用回想当初是在哪个 App 看到的。",
    mapAlt: "Pocklet 地图上的附近收藏地点",
    howTitle: "存下来。找回来。真的去做。",
    mapTitle: "看看附近存过哪些地方",
    featuresTitle: "琐碎的事，都帮你搞定。",
    features: [
      { title: "在哪看到，都能存", description: "从 Instagram、TikTok 或其他地方分享链接，把好发现和其他收藏放在一起。" },
      { title: "贴近生活的分类", description: "吃、去、买、做，也可以创建自己的分类。" },
      { title: "不用记得存在哪里", description: "搜索收藏的名称、笔记、标签、链接，以及可识别的文字。" },
      { title: "在对的时间回来", description: "给不想忘记的事设好提醒。" },
      { title: "喜欢的，留在最爱", description: "把最喜欢的收藏留在手边，就算完成了，还是能轻松找到。" },
      { title: "做完了，也还在", description: "标记完成，把喜欢的加入最爱，随时到历史记录里回顾。" },
    ],
    downloadDescription: "把发现的好东西存起来，这个周末或几个月后想再看看时，都能轻松找回。",
    appStoreComingSoon: "即将推出",
    googlePlayQrAlt: "扫描二维码，到 Google Play 下载 Pocklet",
    plusTitle: "多一点空间，\n少一点琐事。",
    plusDescription: "好发现都存下来，细节交给 AI，提醒时间也能自己决定。",
    plusAutoTitle: "无限收藏与 Auto Details",
    plusAutoDescription: "想存多少都可以。Auto Details 会建议名称、笔记、分类、标签和地点，你可以检查并修改任何信息。",
    plusReminderTitle: "更灵活的提醒",
    plusReminderDescription: "选择确切的提醒时间，还能添加多次提前提醒。",
  },
};
