const english = {
  hero: {
    title1: "Save now.",
    beforeCategory: "",
    afterCategory: "later",
    verbs: { eat: "Eat", go: "Go", buy: "Buy", do: "Do" },
    subtitle: "Keep everything you want to come back to in one place.",
    accessibleTitle: "Save now. Eat, go, buy or do later.",
    pauseAnimation: "Pause animation",
    resumeAnimation: "Resume animation",
    seeHow: "See how it works",
  },
  problem: {
    eyebrow: "Sound familiar?",
    title1: "Something in your apps. Somewhere.",
    example1: "That new café everyone’s talking about.",
    example2: "That concert you want to see in 3 months.",
    pain: "You remember saving them. Just not where.",
    solution: "Your good finds are just a few taps away.",
  },
  how: {
    eyebrow: "IN 3 STEPS",
    title: "How it works",
    step1Title: "Save a find",
    step1Desc: "Share a post, paste a link, or add a screenshot.",
    step2Title: "Add what matters",
    step2Desc: "Add a name, tag, or even pin a location.",
    step3Title: "Come back when it counts",
    step3Desc: "Search for it or set a reminder for the right time.",
  },
  demo: {
    title: "Watch Pocklet in action",
    duration: "25 sec",
    play: "Play demo",
    pause: "Pause demo",
    error: "Try play",
  },
  map: {
    eyebrow: "On the map",
    title: "See what’s nearby",
    description: "Open the map and choose from places you’ve already saved.",
    point1: "Pick a spot and go",
  },
  features: {
    eyebrow: "What’s inside",
    title: "The boring parts, handled",
    categoriesTitle: "Categories & tags",
    categoriesDesc: "Sort it your way",
    searchTitle: "Search",
    searchDesc: "Find it again, fast",
    remindersTitle: "Reminders",
    remindersDesc: "Get a nudge when it matters",
    favouritesTitle: "Favourites & history",
    favouritesDesc: "Keep what you loved. Look back anytime",
  },
  plus: {
    eyebrow: "Pocklet Plus",
    title1: "More room.",
    title2: "Less work.",
    description: "Keep every find, let AI handle the details, and choose when Pocklet brings things back.",
    support: "Unlimited saves. Unlimited Auto Details. Multiple nudges.",
  },
  download: {
    title1: "What you’ve been meaning to do",
    title2: "starts here",
    subtitle: "Give your next good find a home",
    appStorePrefix: "Download on the",
    googlePlayPrefix: "Get it on",
  },
  footer: {
    noAds: "No ads",
    noTracking: "No marketing tracking",
    localFirst: "Local-first by design",
  },
  accessibility: {
    home: "Pocklet home",
    categories: "Pocklet’s starting categories",
    artwork: "Pocklet saved cards for books, a bakery, Pilates, headphones and a weekend in Melbourne, with Auto Details and a reminder",
    map: "Pocklet map with saved places in West Village and the Must Try Lasagna card for Don Angie",
    demo: "Pocklet app demo: save a social post, find it in Home and see saved places on the map",
    social: "Pocklet social media",
    footerNavigation: "Footer navigation",
    legalLinks: "Legal links",
  },
};

type MobileHomepageCopy = typeof english;

export const mobileHomepageCopy: Record<string, MobileHomepageCopy> = {
  en: english,
  "zh-TW": {
    hero: {
      title1: "先存起來。", beforeCategory: "晚點再", afterCategory: "",
      verbs: { eat: "吃", go: "去", buy: "買", do: "做" },
      subtitle: "把想回來看的，都收在同一個地方。", accessibleTitle: "現在先收藏。之後再吃、去、買或做。",
      pauseAnimation: "暫停動畫", resumeAnimation: "繼續動畫", seeHow: "看看怎麼用",
    },
    problem: {
      eyebrow: "是不是很熟悉？", title1: "想做的那件事，\n還躺在某個角落。",
      example1: "那間最近大家都在聊的咖啡廳", example2: "三個月後想去的那場演唱會",
      pain: "明明記得有存下來，要找時卻怎麼都找不到。", solution: "用 Pocklet，幾秒就找得到。",
    },
    how: {
      eyebrow: "3 步就好", title: "怎麼用",
      step1Title: "看到喜歡的就收進來", step1Desc: "分享貼文、貼上連結，或加入截圖。",
      step2Title: "補上重要資訊", step2Desc: "加個名稱、標籤，也可以標記地點。",
      step3Title: "需要時再回來", step3Desc: "直接搜尋，或先設好提醒。",
    },
    demo: { title: "看 Pocklet 實際操作", duration: "25 秒", play: "播放示範", pause: "暫停示範", error: "重試播放" },
    map: {
      eyebrow: "打開地圖", title: "看看附近有什麼",
      description: "附近存過的地方，一眼就看得到。",
      point1: "選個地方，就出發。",
    },
    features: {
      eyebrow: "你會用到的", title: "瑣碎的事，都幫你搞定",
      categoriesTitle: "分類與標籤", categoriesDesc: "想怎麼整理都可以", searchTitle: "搜尋", searchDesc: "想找的，一下就找到",
      remindersTitle: "提醒", remindersDesc: "到時候再提醒你", favouritesTitle: "最愛與紀錄", favouritesDesc: "喜歡的留著，隨時再看",
    },
    plus: {
      eyebrow: "Pocklet Plus", title1: "存得更多，", title2: "整理更少",
      description: "想留的都能存，細節讓 AI 幫你補上，什麼時候提醒也由你決定。",
      support: "收藏不限量。Auto Details 無限用。還能設定多次提醒。",
    },
    download: { title1: "那些一直想做的，", title2: "就從這裡開始", subtitle: "給下一個好發現一個家。", appStorePrefix: "立即下載", googlePlayPrefix: "立即下載" },
    footer: { noAds: "無廣告", noTracking: "無行銷追蹤", localFirst: "以本機儲存為核心" },
    accessibility: {
      home: "Pocklet 首頁", categories: "Pocklet 預設分類",
      artwork: "Pocklet 的書籍、麵包店、皮拉提斯、耳機與墨爾本週末收藏卡片，搭配 Auto Details 與提醒",
      map: "Pocklet 地圖上的西村收藏地點，以及 Don Angie 的 Must Try Lasagna 收藏卡片",
      demo: "Pocklet 操作示範：收藏社群貼文、在首頁找回收藏，再到地圖查看收藏地點", social: "Pocklet 社群平台",
      footerNavigation: "頁尾導覽", legalLinks: "法律資訊",
    },
  },
  "zh-CN": {
    hero: {
      title1: "先存起来。", beforeCategory: "晚点再", afterCategory: "。",
      verbs: { eat: "吃", go: "去", buy: "买", do: "做" },
      subtitle: "把想回头看的，都放在一个地方。", accessibleTitle: "现在先收藏。之后再吃、去、买或做。",
      pauseAnimation: "暂停动画", resumeAnimation: "继续动画", seeHow: "看看怎么用",
    },
    problem: {
      eyebrow: "是不是很熟悉？", title1: "想做的那件事，\n还躺在某个角落。",
      example1: "那家最近大家都在聊的咖啡店", example2: "三个月后想去的那场演唱会",
      pain: "明明记得存过，真要找的时候却怎么都找不到。", solution: "用 Pocklet，几秒就能找到。",
    },
    how: {
      eyebrow: "从这里开始", title: "怎么用",
      step1Title: "看到喜欢的就收进来", step1Desc: "分享内容、粘贴链接，或添加截图。",
      step2Title: "补上重要信息", step2Desc: "加个名称、标签，也可以标记地点。",
      step3Title: "需要时再回来", step3Desc: "直接搜索，或提前设好提醒。",
    },
    demo: { title: "看 Pocklet 实际操作", duration: "25 秒", play: "播放演示", pause: "暂停演示", error: "重试播放" },
    map: {
      eyebrow: "打开地图", title: "看看附近有什么",
      description: "附近存过的地方，一眼就能看到。",
      point1: "选个地方，就出发。",
    },
    features: {
      eyebrow: "你会用到的", title: "琐碎的事，都帮你搞定",
      categoriesTitle: "分类与标签", categoriesDesc: "想怎么整理都可以", searchTitle: "搜索", searchDesc: "想找的，一下就能找到",
      remindersTitle: "提醒", remindersDesc: "到时候再提醒你", favouritesTitle: "最爱与历史记录", favouritesDesc: "喜欢的留着，随时回顾",
    },
    plus: {
      eyebrow: "Pocklet Plus", title1: "存得更多，", title2: "整理更少",
      description: "想存的都能存，细节让 AI 帮你补上，什么时候提醒也由你决定。",
      support: "Auto Details 无限用、收藏不限量，提醒时间也能自定义。",
    },
    download: { title1: "那些一直想做的，", title2: "就从这里开始", subtitle: "这次真的去做", appStorePrefix: "立即下载", googlePlayPrefix: "立即下载" },
    footer: { noAds: "无广告", noTracking: "无营销跟踪", localFirst: "以本地存储为核心" },
    accessibility: {
      home: "Pocklet 首页", categories: "Pocklet 默认分类",
      artwork: "Pocklet 的书籍、面包店、普拉提、耳机与墨尔本周末收藏卡片，搭配 Auto Details 与提醒",
      map: "Pocklet 地图上的西村收藏地点，以及 Don Angie 的 Must Try Lasagna 收藏卡片",
      demo: "Pocklet 操作演示：收藏社交帖子、在首页找回收藏，再到地图查看收藏地点", social: "Pocklet 社交平台",
      footerNavigation: "页脚导航", legalLinks: "法律信息",
    },
  },
};
